export const TARJETAS = [
    {titulo: 'Lo siento', texto: "Lo siento por no darme cuenta que estabas enamorada de mi"},
    {titulo: 'Te quiero', texto: "Tanto que aprendi a decir tu nombre antes que el mio"},
    {titulo: 'Te prometo', texto: "Que yo jamas te hare una promesa. Que no pretenda cumplir"},
    {titulo: 'Eres', texto: "Lo mas bonito del mundo"},
    {titulo: 'Tengo ', texto: "Miedo de lastimarte, de no llegar a ser lo mejor para ti"},
    {titulo: 'Tengo', texto: "Ganas de hacer una vida contigo"},
    {titulo: 'Nos diran', texto: "no seas ilus@. Solo te quiere por....."},
    {titulo: 'Solo podremos', texto: "Avanzar diciendo 'mal por ti' "},
    {titulo: 'No', texto: "No hagamos caso a la gente, disfrutemos sin remordimientos"},
    {titulo: 'La vida', texto: "Es una aventura"},
    {titulo: 'Unete a mi', texto: "Y hagamos de esta odisea una historia romantica de la que hagan una pelicula"},
    {titulo: 'En este mundo', texto: "Tan superficial, tan loco, tan mentiroso"},
    {titulo: 'Eres mi VERDAD', texto: "Por eso"},
    {titulo: 'Quiero'},
    {titulo: 'Que sepas que.......'},
]